title: Critical Making Curriculum
#subtitle:
email: criticalmaking@lists.zsi.at
twitter: https://twitter.com/critical_making
#chat:
description: > # this means to ignore newlines until "baseurl:"
  Critical Making Resources
baseurl: "/cm-curriculum" # the subpath of your site, e.g. /blog
url: "https://alexanderkutschera.com" # the base hostname & protocol for your site
github:
  repo: "vektorious/cm-curriculum"
  branch: "gh-pages"


collections:
  articles:
    output: true
permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

# variables
video: "<span class=\"video-player\"></span>"
assignment: "<span class=\"assignment\">Assignment: </span>"
theme: jekyll-theme-minimal
